import "./globals.css";
import { Inter, Urbanist } from "next/font/google";
import Navbar from "@/components/shared/navbar";
const urbanist = Urbanist({ subsets: ["latin"] });
import AuthProvider from "@/components/shared/authprovider";
import { Toaster } from "react-hot-toast";
import { ClerkProvider } from "@clerk/nextjs";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={urbanist.className}>
        <ClerkProvider>
          <div className="px-4 md:px-32">
            <Navbar />
            {children}
          </div>
          <Toaster position="bottom-center" />
        </ClerkProvider>
      </body>
    </html>
  );
}
