import "./globals.css";
import { Inter, Urbanist } from "next/font/google";
import Navbar from "@/components/shared/navbar";
const urbanist = Urbanist({ subsets: ["latin"] });
import { Toaster } from "react-hot-toast";
import SessionProvider from "@/components/shared/sessionprovider";
import { getServerSession } from "next-auth";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={urbanist.className}>
        <SessionProvider session={session}>
          <div className="px-4 container md:max-w-6xl mx-auto">
            <Navbar />
            {children}
          </div>
          <Toaster position="bottom-center" />
        </SessionProvider>
      </body>
    </html>
  );
}
